version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 255321081393.dkr.ecr.ap-southeast-2.amazonaws.com/rhenium-ui
  build:
    commands:
      - docker build -t rhenium-ui:latest .
      - docker tag rhenium-ui:latest 255321081393.dkr.ecr.ap-southeast-2.amazonaws.com/rhenium-ui:latest
  post_build:
    commands:
      - docker push 255321081393.dkr.ecr.ap-southeast-2.amazonaws.com/rhenium-ui:latest
      - printf '[{"name":rhenium-ecs-task,"imageUri":"%s"}]' <ECR_URL> > imagedefinitions.json
artifacts:
  files: imagedefinitions.json